### ISSUE TITLE
help with editing the dll file

### ISSUE THREAD

**Issue by SnakeDeath** [Failzuma/JustAsPlanned#1]
can you plaese go on some detail on what to edit in the dll file with the hex editor ? 
thx in advance

**Comment by Failzuma** [comment]
Regarding your question, `what to edit in the dll file` is the sequence of bytes you need to find by reversing the GameAssembly.dll
luckily, you can find the [pattern here](https://github.com/Eimaen/JustAsPlanned/blob/03d65eaeea1630584e75f2dcd5376a48d5df802f/JustAsPlanned/MuseDash.cs#L14)
